### ISSUE TITLE
Backflow Reports RP test

### ISSUE THREAD

**Issue by WatersPaul** [unum15/tasca.vuejs#33]
Set up the RP test section Differential Pressure to show test results on Opened at after the #sign. 

- If the test results are >=2 both checkboxes need to be unchecked. 
- If the test value is <2 and >0 then check the Open under 2#box. 
- If the test value is 0 check the Did not open box.  

If the second test is Blank Mark the RP test section under Check Valve #2 as follows; 

- PSI should be Blank, 
- Close Tight unchecked, 
- and Leaked unchecked.  

Mark the section Check Valve #1; 

- PSi blank line, 
- Closed Tight box unchecked 
- and Leaked unchecked  

 If the second test number is >= to the first test number. Mark the RP test section under Check Valve #2; 

- PSI remove the # and replace it with OK, 
- Close Tight checked 
- and Leaked unchecked.

Mark the section Check Valve #1; 

- PSi with the test #2 value 
- and Closed Tight box Checked 
- and Leaked Unchecked

  
If the second test number is < to the first test number Mark the RP test section under Check Valve #2 as follows; 

- 
- PSI should be Blank, 
- Close Tight unchecked,
- and Leaked checked.

Mark the section Check Valve #1; 

- PSi with the test #2 value 
- and Closed Tight box unchecked. 
- and Leaked checked  

- If the first test value is >= 2 AND the second test number is >= to the first test number + 5 show test as satisfactory.  
- If the first test value is < 2 OR the second test number is < to the first test number + 5 OR the second test is blank show test as unsatisfactory.

**Comment by unum15** [comment]
See the question marks I added above. I'm guessing that that should read unchecked.

**Comment by unum15** [comment]
You have expectations for >= and <= those over lap.  You have to pick one.

**Comment by unum15** [comment]
Do you want to be able to change these check marks? Or are they always set?
